// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0C2DjnrA-AoUmNdRux95ekLz-KGnE_nQ',
    appId: '1:957057067024:web:ea56e414486630ce074295',
    messagingSenderId: '957057067024',
    projectId: 'taskms-8040d',
    authDomain: 'taskms-8040d.firebaseapp.com',
    storageBucket: 'taskms-8040d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSMWMcds3GuTCg4ruDdtTFA_W4QzozhD4',
    appId: '1:957057067024:android:891c90d932fe5758074295',
    messagingSenderId: '957057067024',
    projectId: 'taskms-8040d',
    storageBucket: 'taskms-8040d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7LtTB9xFe0RzEnTFb_r8ER-8c0bRmHrI',
    appId: '1:957057067024:ios:474ff9eff9dc1529074295',
    messagingSenderId: '957057067024',
    projectId: 'taskms-8040d',
    storageBucket: 'taskms-8040d.firebasestorage.app',
    iosBundleId: 'com.example.taskms',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0C2DjnrA-AoUmNdRux95ekLz-KGnE_nQ',
    appId: '1:957057067024:web:d45f40a857043047074295',
    messagingSenderId: '957057067024',
    projectId: 'taskms-8040d',
    authDomain: 'taskms-8040d.firebaseapp.com',
    storageBucket: 'taskms-8040d.firebasestorage.app',
  );
}
